### ISSUE TITLE
How to reproduce the results in Figure 5？

### ISSUE THREAD

**Issue by 943fansi** [xiao-he/OneShotSTL#1]
I am very interested in your work. Will the code regarding the Figure 5 results be posted?

**Comment by xiao-he** [comment]
Thanks for your interest for our paper. Yes, we plan to release the code to reproduce all the results. But, I cannot give you a timeline currently due to company policy.

**Comment by 943fansi** [comment]
@xiao-he Thanks for your reply. I'm looking forward to the final code.

**Comment by xiao-he** [comment]
@943fansi code updated.

**Comment by 943fansi** [comment]
@xiao-he Thanks.
